use anyhow::{anyhow, Context, Result};
use camino::{Utf8Path, Utf8PathBuf};
use cargo_metadata::{CargoOpt::AllFeatures, MetadataCommand};
use clap::Parser;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashSet};
use std::io::{BufReader, Write};
use std::process::Command;

const CONFIG_KEY: &str = "vendor-filter";
const SELF_NAME: &str = "vendor-filterer";
const VENDOR_DEFAULT_PATH: &str = "vendor";

/// This is the .cargo-checksum.json in a crate/package.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
struct CargoChecksums {
    files: BTreeMap<String, String>,
    package: String,
}

/// The minimal bits of Cargo.toml we need.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
struct CargoManifest {
    package: CargoPackage,
    features: BTreeMap<String, Vec<String>>,
}

/// The minimal bits of the `[package]` section in Cargo.toml we need.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
struct CargoPackage {
    name: String,
    version: String,
    edition: String,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
enum OutputTarget {
    Dir,
    //    Tar,
}

impl Default for OutputTarget {
    fn default() -> Self {
        Self::Dir
    }
}

impl clap::ValueEnum for OutputTarget {
    fn value_variants<'a>() -> &'a [Self] {
        &[Self::Dir]
    }

    fn to_possible_value<'a>(&self) -> Option<clap::PossibleValue<'a>> {
        match self {
            Self::Dir => Some(clap::PossibleValue::new("dir")),
        }
    }
}

#[derive(PartialEq, Eq, Deserialize, Default, Debug)]
#[serde(rename_all = "kebab-case")]
struct VendorFilter {
    platforms: Option<Vec<String>>,
    all_features: Option<bool>,
}

/// Enhanced `cargo vendor` with filtering
#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
struct Args {
    /// Only include crates for these targets.
    ///
    /// For example, `x86_64-unknown-linux-gnu`.
    #[clap(long)]
    platform: Option<Vec<String>>,

    /// Enable all features
    #[clap(long)]
    all_features: Option<bool>,

    #[clap(long, value_parser, default_value = "dir")]
    format: OutputTarget,

    /// The output path
    #[clap(default_value = VENDOR_DEFAULT_PATH)]
    path: Utf8PathBuf,
}

// cargo does autodiscovery of the workspace, and as far as I can tell
// there's no way to turn this off via environment variable or CLI.
// So...forcibly hack in a dummy workspace value.
fn inject_dummy_workspace(path: &Utf8Path) -> Result<()> {
    let cargo_path = path.join("Cargo.toml");
    let cargo_toml =
        std::fs::read_to_string(&cargo_path).with_context(|| format!("Writing {path}"))?;
    let cargo_toml = cargo_toml.replace("[package]", "[workspace]\n[package]");
    std::fs::write(&cargo_path, cargo_toml)?;
    Ok(())
}

/// Given a directory for a package generated by `cargo vendor`, replace it
/// with an empty package.  This follows the approach suggested here
/// https://github.com/rust-lang/cargo/issues/7058#issuecomment-697074341
///
/// Entirely removing the crates would require editing the dependency graph,
/// which gets into more work.
fn replace_with_stub(path: &Utf8Path) -> Result<()> {
    inject_dummy_workspace(path).context("Injecting dummy [workspace]")?;

    // Gather metadata for just this dependency, not recursively.
    let mut command = MetadataCommand::new();
    command.current_dir(path);
    command.no_deps();
    let meta = command.exec().context("Executing cargo metadata")?;

    let root = meta
        .packages
        .get(0)
        .ok_or_else(|| anyhow!("Failed to find root package in {path}"))?;
    let name = &root.name;
    let version = &root.version;
    let edition = &root.edition;
    let checksums_path = path.join(".cargo-checksum.json");
    let checksums = std::fs::File::open(&checksums_path).map(BufReader::new)?;
    let mut checksums: CargoChecksums =
        serde_json::from_reader(checksums).with_context(|| format!("Parsing {checksums_path}"))?;

    // Clear out everything and replace it with a fresh directory with a new `src/`
    // subdir.
    std::fs::remove_dir_all(path)?;
    std::fs::create_dir_all(path.join("src"))?;
    // Also empty out the file checksums, but keep the overall package checksum.
    checksums.files.clear();

    // Helper to both write a file and compute its sha256, storing it in the
    // cargo checksum list.
    let mut writef = |target: &Utf8Path, contents: &str| {
        let fullpath = path.join(target);
        std::fs::write(&fullpath, contents)?;
        let digest =
            openssl::hash::hash(openssl::hash::MessageDigest::sha256(), contents.as_bytes())?;
        let digest = hex::encode(digest);
        checksums.files.insert(fullpath.to_string(), digest);
        Ok::<_, anyhow::Error>(())
    };
    let features = root
        .features
        .iter()
        .map(|(k, _)| (k.clone(), Vec::new()))
        .collect();
    let new_manifest = CargoManifest {
        package: CargoPackage {
            name: name.to_string(),
            edition: edition.to_string(),
            version: version.to_string(),
        },
        features,
    };
    let new_manifest = toml::to_string(&new_manifest)?;
    // An empty Cargo.toml
    writef(Utf8Path::new("Cargo.toml"), &new_manifest)?;
    // And an empty source file
    writef(Utf8Path::new("src/lib.rs"), "")?;
    // Finally, serialize the new checksums
    let mut w = std::fs::File::create(checksums_path).map(std::io::BufWriter::new)?;
    serde_json::to_writer(&mut w, &checksums)?;
    w.flush()?;
    Ok(())
}

impl VendorFilter {
    fn parse_json(meta: &serde_json::Value) -> Result<Option<Self>> {
        let meta = meta.as_object().and_then(|o| o.get(CONFIG_KEY));
        let meta = if let Some(m) = meta {
            m
        } else {
            return Ok(None);
        };
        let v: Self = serde_json::from_value(meta.clone())?;
        Ok(Some(v))
    }

    fn parse_args(args: &Args) -> Option<Self> {
        let args_unset = args.platform.is_none() && args.all_features.is_none();
        (!args_unset).then(|| Self {
            platforms: args.platform.clone(),
            all_features: args.all_features,
        })
    }
}

fn gather_config(args: &Args) -> Result<Option<VendorFilter>> {
    // Accept config from arguments first
    if let Some(f) = VendorFilter::parse_args(args) {
        return Ok(Some(f));
    };
    let meta = MetadataCommand::new()
        .exec()
        .context("Executing cargo metadata (first run)")?;
    meta.root_package()
        .and_then(|r| VendorFilter::parse_json(&r.metadata).transpose())
        .transpose()
}

fn run() -> Result<()> {
    let mut args = std::env::args().collect::<Vec<_>>();
    // When invoked as a subcommand of `cargo`, it passes the subcommand name as
    // the second argument, which is a bit inconvenient for us.  Special case that.
    if args.get(1).map(|s| s.as_str()) == Some(SELF_NAME) {
        args.remove(1);
    }

    let args = Args::parse_from(args);

    let (had_config, config) = if let Some(c) = gather_config(&args)? {
        (true, c)
    } else {
        (false, VendorFilter::default())
    };
    if !had_config {
        eprintln!("Notice: No vendor filtering enabled");
    }

    let mut command = MetadataCommand::new();
    if config.all_features.unwrap_or_default() {
        command.features(AllFeatures);
    }
    // TODO: verify by cross checking all tier1 platforms that the dependency set is exactly
    // the same.

    let filter = match &config.platforms.as_deref() {
        None | Some([]) => None,
        Some([p]) => Some(p),
        Some(_) => anyhow::bail!("Specifying multiple targets is not currently supported"),
    };

    let other_args = filter.map(|s| format!("--filter-platform={s}")).into_iter();
    command.other_options(other_args.collect::<Vec<_>>());
    let meta = command.exec().context("Executing cargo metadata")?;
    let packages = &meta.packages;

    if args.path.exists() {
        anyhow::bail!("Refusing to operate on extant directory: {}", args.path);
    }

    let status = Command::new("cargo")
        .args(&["vendor"])
        .arg(args.path.as_str())
        .status()?;
    if !status.success() {
        anyhow::bail!("Failed to execute cargo vendor: {:?}", status);
    }

    let root = meta.root_package();

    let mut pkgs_by_name = BTreeMap::<_, Vec<_>>::new();
    for pkg in packages {
        let name = pkg.name.as_str();
        // Skip ourself
        if let Some(root) = root {
            if pkg.id == root.id {
                continue;
            }
        }
        // Also skip anything not from crates.io
        if pkg
            .source
            .as_ref()
            .filter(|source| source.is_crates_io())
            .is_none()
        {
            eprintln!("Skipping {name}");
            continue;
        }

        let v = pkgs_by_name.entry(name).or_default();
        let name_version = format!("{name}-{}", pkg.version);
        v.push((name_version, pkg));
    }

    let mut unversioned_packages = BTreeMap::new();
    let mut multiversioned_packages = BTreeMap::new();
    for (name, versions) in pkgs_by_name {
        let mut versions = versions.into_iter().peekable();
        let first = versions.next().unwrap();
        if versions.peek().is_some() {
            for (version, pkg) in std::iter::once(first).chain(versions) {
                multiversioned_packages.insert(version, pkg);
            }
        } else {
            assert!(unversioned_packages.insert(name, first.1).is_none());
        }
    }

    let mut package_filenames = BTreeMap::new();
    for (name, pkg) in unversioned_packages {
        let name_path = args.path.join(name);
        if !name_path.exists() {
            anyhow::bail!("Failed to find vendored dependency: {name}");
        }
        package_filenames.insert(name.to_string(), pkg);
    }

    // When writing out packages that have multiple versions, `cargo vendor`
    // appears to use an algorithm where the first (or highest version?)
    // is just $name, then all other versions end up as $name-$version.
    // We build up a map of those here to their original package.
    for (namever, pkg) in multiversioned_packages {
        let name = &pkg.name;
        let namever_path = args.path.join(&namever);
        let name_path = args.path.join(name);
        if namever_path.exists() {
            package_filenames.insert(namever, pkg);
        } else if name_path.exists() {
            package_filenames.insert(pkg.name.to_string(), pkg);
        } else {
            anyhow::bail!("Failed to find vendored dependency: {namever}");
        }
    }

    let mut pbuf = args.path.clone();
    let mut unreferenced = HashSet::new();
    // First pass, find and physically delete unreferenced packages, also
    // gathering up the set of packages that we deleted.
    for entry in args.path.read_dir_utf8()? {
        let entry = entry?;
        let name = entry.file_name();
        pbuf.push(name);

        if !package_filenames.contains_key(name) {
            replace_with_stub(&pbuf).with_context(|| format!("Replacing with stub: {name}"))?;
            eprintln!("Replacing unreferenced package with stub: {name}");
            assert!(unreferenced.insert(name.to_string()));
        }

        let r = pbuf.pop();
        debug_assert!(r);
    }

    if !had_config {
        eprintln!("Notice: No vendor filtering enabled");
    } else if let Some(platforms) = config.platforms.as_deref() {
        eprintln!("Filtered to target platforms: {:?}", platforms);
    }

    Ok(())
}

fn main() {
    if let Err(e) = run() {
        eprintln!("{:#}", e);
        std::process::exit(1);
    }
}

#[test]
fn test_parse_config() {
    let valid = vec![
        serde_json::json!({}),
        serde_json::json!({ "platforms": ["aarch64-unknown-linux-gnu"]}),
        serde_json::json!({ "platforms": ["aarch64-unknown-linux-gnu"], "all-features": true}),
    ];
    for case in valid {
        let _: VendorFilter = serde_json::from_value(case).unwrap();
    }
}
